"""Build the polished, multi-sheet Excel workbook that's the actual
business deliverable a CRM/ops team would open — not just a data dump.

Uses openpyxl directly (not just `DataFrame.to_excel`) so the workbook gets
real formatting: styled headers, frozen panes, sensible column widths,
conditional formatting on the numbers that matter (material shortages,
at-risk accounts), and native embedded Excel charts (not images) that a
user can still click into and edit.
"""

from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd
from openpyxl import Workbook
from openpyxl.chart import BarChart, LineChart, PieChart, Reference
from openpyxl.formatting.rule import CellIsRule
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.worksheet import Worksheet

logger = logging.getLogger(__name__)

HEADER_FILL = PatternFill(start_color="1F2A44", end_color="1F2A44", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True, size=11)
TITLE_FONT = Font(bold=True, size=16, color="1F2A44")
SUBTITLE_FONT = Font(size=10, color="666666", italic=True)
ACCENT_FILL = PatternFill(start_color="E8EDF7", end_color="E8EDF7", fill_type="solid")
RISK_FILL = PatternFill(start_color="FBE1E1", end_color="FBE1E1", fill_type="solid")
RISK_FONT = Font(color="9C1F1F", bold=True)


def _write_table(ws: Worksheet, df: pd.DataFrame, start_row: int = 1, start_col: int = 1) -> int:
    """Write a DataFrame as a styled table starting at (start_row, start_col).
    Returns the row index just after the table."""
    df = df.copy()
    for col in df.columns:
        if (
            pd.api.types.is_datetime64_any_dtype(df[col])
            or "date" in col.lower()
            or "period_start" in col.lower()
        ):
            try:
                df[col] = pd.to_datetime(df[col]).dt.date
            except (ValueError, TypeError):
                pass

    for j, col_name in enumerate(df.columns):
        cell = ws.cell(
            row=start_row, column=start_col + j, value=str(col_name).replace("_", " ").title()
        )
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center")

    for i, (_, row) in enumerate(df.iterrows()):
        for j, val in enumerate(row):
            if isinstance(val, float) and pd.notna(val):
                val = round(val, 2)
            ws.cell(row=start_row + 1 + i, column=start_col + j, value=val)

    ws.freeze_panes = ws.cell(row=start_row + 1, column=start_col)
    for j, col_name in enumerate(df.columns):
        header_len = len(str(col_name).replace("_", " "))
        body_len = df[col_name].astype(str).str.len().max() if len(df) else 0
        target = max(header_len, body_len) + 2
        width = max(10, min(36, target))
        ws.column_dimensions[get_column_letter(start_col + j)].width = width

    return start_row + 1 + len(df)


def _title(ws: Worksheet, title: str, subtitle: str = "") -> None:
    ws["A1"] = title
    ws["A1"].font = TITLE_FONT
    if subtitle:
        ws["A2"] = subtitle
        ws["A2"].font = SUBTITLE_FONT


def build_workbook(
    monthly_summary: pd.DataFrame,
    forecast: pd.DataFrame,
    production_plan: pd.DataFrame,
    mrp: pd.DataFrame,
    accuracy: pd.DataFrame,
    lead_funnel_df: pd.DataFrame,
    opportunity_funnel_df: pd.DataFrame,
    win_rate_df: pd.DataFrame,
    rep_leaderboard_df: pd.DataFrame,
    lose_reasons_df: pd.DataFrame,
    at_risk_df: pd.DataFrame,
    products: pd.DataFrame,
    out_path: str,
) -> None:
    wb = Workbook()
    wb.remove(wb.active)

    _build_summary_sheet(wb, monthly_summary, accuracy)
    _build_forecast_sheet(wb, forecast, products)
    _build_production_sheet(wb, production_plan, monthly_summary)
    _build_mrp_sheet(wb, mrp)
    _build_crm_sheet(wb, lead_funnel_df, opportunity_funnel_df, win_rate_df, lose_reasons_df)
    _build_rep_sheet(wb, rep_leaderboard_df)
    _build_at_risk_sheet(wb, at_risk_df)

    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    wb.save(out_path)
    logger.info("Wrote Excel workbook to %s", out_path)


def _build_summary_sheet(
    wb: Workbook, monthly_summary: pd.DataFrame, accuracy: pd.DataFrame
) -> None:
    ws = wb.create_sheet("Executive Summary")
    _title(
        ws,
        "S&OP Executive Summary",
        "Pars Voltage Battery Industries Co. — generated by the CRM + S&OP planning engine",
    )

    total_forecast = int(monthly_summary["forecast_units"].sum())
    total_allocated = int(monthly_summary["allocated_units"].sum())
    fill_rate = total_allocated / total_forecast if total_forecast else 0
    revenue_lost = int(monthly_summary["revenue_lost_irr"].sum())
    overall_row = accuracy[accuracy["line_id"] == "__OVERALL__"]
    wape = float(overall_row["wape"].iloc[0]) if not overall_row.empty else float("nan")

    kpis = [
        ("Forecast horizon (months)", monthly_summary["period_start"].nunique()),
        ("Total forecast units", f"{total_forecast:,}"),
        ("Total planned (allocated) units", f"{total_allocated:,}"),
        ("Overall fill rate", f"{fill_rate:.1%}"),
        ("Revenue at risk from capacity limits (IRR)", f"{revenue_lost:,}"),
        ("Statistical forecast backtest WAPE", f"{wape:.1%}" if pd.notna(wape) else "n/a"),
    ]
    row = 4
    for label, value in kpis:
        ws.cell(row=row, column=1, value=label).font = Font(bold=True)
        ws.cell(row=row, column=2, value=value)
        ws.cell(row=row, column=1).fill = ACCENT_FILL
        row += 1

    row += 1
    ws.cell(row=row, column=1, value="Monthly Summary").font = Font(bold=True, size=13)
    row += 1
    table_end = _write_table(ws, monthly_summary, start_row=row)

    chart = LineChart()
    chart.title = "Fill rate by month"
    chart.y_axis.title = "Fill rate"
    chart.x_axis.title = "Month"
    fill_col = monthly_summary.columns.get_loc("fill_rate") + 1
    data = Reference(ws, min_col=fill_col, min_row=row, max_row=table_end - 1)
    cats = Reference(ws, min_col=1, min_row=row + 1, max_row=table_end - 1)
    chart.add_data(data, titles_from_data=True)
    chart.set_categories(cats)
    ws.add_chart(chart, f"A{table_end + 2}")

    ws.column_dimensions["A"].width = 40
    ws.column_dimensions["B"].width = 22


def _build_forecast_sheet(wb: Workbook, forecast: pd.DataFrame, products: pd.DataFrame) -> None:
    ws = wb.create_sheet("Demand Forecast")
    _title(
        ws,
        "Demand Forecast",
        "Statistical baseline (line-level) + CRM open-pipeline overlay, by SKU and month",
    )

    merged = forecast.merge(products[["product_id", "product_name", "category"]], on="product_id")
    cols = [
        "period_start",
        "line_id",
        "product_id",
        "product_name",
        "category",
        "baseline_units",
        "pipeline_units",
        "forecast_units",
    ]
    table_end = _write_table(ws, merged[cols], start_row=4)

    by_line_month = forecast.groupby(["line_id", "period_start"], as_index=False)[
        "forecast_units"
    ].sum()
    pivot = by_line_month.pivot(
        index="period_start", columns="line_id", values="forecast_units"
    ).reset_index()
    pivot_row = table_end + 2
    ws.cell(row=pivot_row, column=1, value="Forecast Units by Line").font = Font(bold=True, size=13)
    pivot_end = _write_table(ws, pivot, start_row=pivot_row + 1)

    chart = BarChart()
    chart.type = "col"
    chart.grouping = "clustered"
    chart.title = "Forecast units by line, by month"
    data = Reference(
        ws, min_col=2, max_col=pivot.shape[1], min_row=pivot_row + 1, max_row=pivot_end - 1
    )
    cats = Reference(ws, min_col=1, min_row=pivot_row + 2, max_row=pivot_end - 1)
    chart.add_data(data, titles_from_data=True)
    chart.set_categories(cats)
    ws.add_chart(chart, f"A{pivot_end + 2}")


def _build_production_sheet(
    wb: Workbook, production_plan: pd.DataFrame, monthly_summary: pd.DataFrame
) -> None:
    ws = wb.create_sheet("Production Plan")
    _title(
        ws,
        "Production Plan",
        "Capacity- and labor-constrained allocation (linear program), by line/SKU/month",
    )
    table_end = _write_table(ws, production_plan, start_row=4)

    unmet_col = production_plan.columns.get_loc("unmet_units") + 1
    rng = f"{get_column_letter(unmet_col)}5:{get_column_letter(unmet_col)}{table_end}"
    ws.conditional_formatting.add(
        rng, CellIsRule(operator="greaterThan", formula=["0"], fill=RISK_FILL, font=RISK_FONT)
    )


def _build_mrp_sheet(wb: Workbook, mrp: pd.DataFrame) -> None:
    ws = wb.create_sheet("Material Requirements")
    _title(
        ws,
        "Material Requirements Plan (MRP)",
        "Monthly requirement vs. projected on-hand, with purchase recommendations",
    )
    table_end = _write_table(ws, mrp, start_row=4)

    below_col = mrp.columns.get_loc("below_safety_stock") + 1
    rng = f"{get_column_letter(below_col)}5:{get_column_letter(below_col)}{table_end}"
    ws.conditional_formatting.add(
        rng, CellIsRule(operator="equal", formula=["TRUE"], fill=RISK_FILL, font=RISK_FONT)
    )


def _build_crm_sheet(
    wb: Workbook,
    lead_funnel_df: pd.DataFrame,
    opportunity_funnel_df: pd.DataFrame,
    win_rate_df: pd.DataFrame,
    lose_reasons_df: pd.DataFrame,
) -> None:
    ws = wb.create_sheet("CRM Pipeline & Funnel")
    _title(
        ws,
        "CRM Pipeline & Funnel Analytics",
        "Dynamics-365-style leads -> opportunities -> won/lost",
    )

    row = 4
    ws.cell(row=row, column=1, value="Lead Conversion by Source").font = Font(bold=True, size=13)
    row += 1
    lf_end = _write_table(ws, lead_funnel_df, start_row=row)

    row = lf_end + 2
    ws.cell(row=row, column=1, value="Win Rate by Account Segment").font = Font(bold=True, size=13)
    row += 1
    wr_start = row
    wr_end = _write_table(ws, win_rate_df, start_row=row)

    win_chart = BarChart()
    win_chart.title = "Win rate by account segment"
    win_col = win_rate_df.columns.get_loc("win_rate") + 1
    data = Reference(ws, min_col=win_col, min_row=wr_start, max_row=wr_end - 1)
    cats = Reference(ws, min_col=1, min_row=wr_start + 1, max_row=wr_end - 1)
    win_chart.add_data(data, titles_from_data=True)
    win_chart.set_categories(cats)
    ws.add_chart(win_chart, f"A{wr_end + 2}")

    row = wr_end + 18
    ws.cell(row=row, column=1, value="Lost Opportunity Reasons").font = Font(bold=True, size=13)
    row += 1
    lr_start = row
    lr_end = _write_table(ws, lose_reasons_df, start_row=row)

    pie = PieChart()
    pie.title = "Lost opportunity reasons"
    data = Reference(ws, min_col=2, min_row=lr_start, max_row=lr_end - 1)
    cats = Reference(ws, min_col=1, min_row=lr_start + 1, max_row=lr_end - 1)
    pie.add_data(data, titles_from_data=True)
    pie.set_categories(cats)
    ws.add_chart(pie, f"D{lr_start}")


def _build_rep_sheet(wb: Workbook, rep_leaderboard_df: pd.DataFrame) -> None:
    ws = wb.create_sheet("Sales Rep Leaderboard")
    _title(ws, "Sales Rep Leaderboard", "Ranked by won pipeline value")
    _write_table(ws, rep_leaderboard_df, start_row=4)


def _build_at_risk_sheet(wb: Workbook, at_risk_df: pd.DataFrame) -> None:
    ws = wb.create_sheet("At-Risk Accounts")
    _title(ws, "At-Risk Accounts", "Open service case AND no order in 90+ days")
    table_end = _write_table(ws, at_risk_df, start_row=4)

    risk_col = at_risk_df.columns.get_loc("at_risk") + 1
    rng = f"{get_column_letter(risk_col)}5:{get_column_letter(risk_col)}{table_end}"
    ws.conditional_formatting.add(
        rng, CellIsRule(operator="equal", formula=["TRUE"], fill=RISK_FILL, font=RISK_FONT)
    )
